services:
  rabbitmq:
    image: rabbitmq:management
    expose:
      - 5672
      - 15672

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"

  eureka:
    build:
      context: ./tot-eureka-server
      dockerfile: Dockerfile
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
    expose:
      - 8761

  auth-api:
    build:
      context: ./tot-auth-api
      dockerfile: Dockerfile
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
    expose:
      - 8082
    depends_on:
      - rabbitmq
      - postgres
      - eureka

  profile-api:
    build:
      context: ./tot-profile-api
      dockerfile: Dockerfile
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
    expose:
      - 8081
    depends_on:
      - rabbitmq
      - postgres
      - eureka

  post-api:
    build:
      context: ./tot-post-api
      dockerfile: Dockerfile
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
    expose:
      - 8777
    depends_on:
      - rabbitmq
      - postgres
      - eureka
      - profile-api

  gateway:
    build:
      context: ./tot-cloud-gateway
      dockerfile: Dockerfile
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
    ports:
      - "8080:8080"
    depends_on:
      - auth-api
      - profile-api
      - post-api
      - eureka